### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by mergik**

### CODE REVIEW

**Comment by bravemaster3** [comment]
Was the simple shell directory removed on purpose?

**Comment by mergik** [comment]
> Was the simple shell directory removed on purpose?

Yes

**Comment by bravemaster3** [comment]
Okay.
I guess something to do with ALX copyrights then.
But doesn't it apply also to the other projects?

**Comment by mergik** [comment]
> But doesn't it apply also to the other projects?

 As far as I know those were created by students. Don't quote me on that.

**Comment by bravemaster3** [comment]
Oh okay.
I get it.
Thanks.
/Koffi

**Pull request merged**
